name = "linkedai"
main = "src/index.ts"
compatibility_date = "2025-05-30"

[assets]
directory = "./public"

[[routes]]
pattern = "mcp.datthemaster.com/linkedai*"
zone_name = "datthemaster.com"

[[kv_namespaces]]
binding = "KV"
id = "20c26c73bdd04670b7335b2bf5f8efdd"
